In [11]:
import numpy as np

In [2]:
list_1=[1,2,3,4,5]
print(list_1,type(list_1))

[1, 2, 3, 4, 5] <class 'list'>


In [3]:
arr=np.array(list_1)
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
import time

In [8]:
size=10_000_000
list_data=list(range(size))

start=time.time()
sq_list=[x**2 for x in list_data]
end=time.time()
print(f"Time taken = {end-start}")

Time taken = 0.9654743671417236


In [9]:
np_arr=np.array(list_data)
start=time.time()
sq_arr=np_arr**2
end=time.time()
print(f"Time taken = {end-start}")



Time taken = 0.026343345642089844


In [11]:
import sys

print(f"Size of list is {sys.getsizeof(list_data)*len(list_data)} bytes")
print(f"Size of array is {np_arr.nbytes} bytes")

Size of list is 800000560000000 bytes
Size of array is 80000000 bytes


In [12]:
#Arrays
arr1=np.array([1,2,3,4])
print(arr1,type(arr1),arr1.shape,arr1.dtype)

arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2,type(arr2),arr2.shape,arr2.dtype)

arr3=np.array([1,2,3,4,"prime"])
print(arr3,type(arr3),arr3.shape,arr3.dtype)

[1 2 3 4] <class 'numpy.ndarray'> (4,) int64
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'> (3, 4) int64
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> (5,) <U21


In [25]:
#prefill
arr4=np.zeros((2,3),dtype="int64")  #this dtype is used to provide data type while creating arr from scratch
print(arr4,arr4.shape)

arr5=np.ones((4,3))
print(arr5,arr5.shape)

#prefill with value
arr6=np.full((3,4),100)
print(arr6,arr6.shape)

#identity matrix
arr7=np.eye(3)
print(arr7,arr7.shape)

#range elements
arr8=np.arange(1,100,5)
print(arr8,arr8.shape)

#evenly spread values means deivide in equal parts
arr9=np.linspace(1,100,4)
print(arr9,arr9.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (4, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96] (20,)
[  1.  34.  67. 100.] (4,)


In [31]:
#properties
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.shape) #row(m) X column(n)
print(arr.size) #total elements
print(arr.dtype) #data type
print(arr.ndim)  #2D,3D etc.

floatarr=arr.astype(np.float64) #type casting (converting arr to diffrent data type)  

print(floatarr,floatarr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12
int64
2
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] float64


In [61]:
#important operations

#reshaping

arr10=np.array([[1,2,1,4],[5,6,0,8],[9,10,11,12]])
print(arr10,arr10.shape)

reshape_arr=arr10.reshape(4,3)
print(reshape_arr,reshape_arr.shape)  #reshpaing can be done with limitaion like we cannot conver 3X4 array to 5X3 etc.

flattened=arr10.flatten()
print(flattened,flattened.shape)

#indexing

print(flattened[0])  #on 1D array
print(flattened[3])

print(arr10[0][1]) #on 2D array

#fancy indexing

inx=[1,2,4]
print("fancy ",flattened[inx])

#boolean indexing (it provides all true values not false)

print("boolean index\n",arr10<=3) #comparing values
print("boolean index",arr10[arr10>2]) #comparing values

#slicing

print("slicing = ",flattened[0:8:2])


[[ 1  2  1  4]
 [ 5  6  0  8]
 [ 9 10 11 12]] (3, 4)
[[ 1  2  1]
 [ 4  5  6]
 [ 0  8  9]
 [10 11 12]] (4, 3)
[ 1  2  1  4  5  6  0  8  9 10 11 12] (12,)
1
4
2
fancy  [2 1 5]
boolean index
 [[ True  True  True False]
 [False False  True False]
 [False False False False]]
boolean index [ 4  5  6  8  9 10 11 12]
slicing =  [1 1 5 0]


In [68]:
#copy vs View

#in list when we apply slicing or any operaton it create another list

nums=[1,2,3,4,5,6]
slic=nums[2:5]
print("list:",slic)

slic[0]=10
print("list:",slic)
print("list:",nums)  #that means it create copy of list


# in array it does not create it view

nums=np.array([1,2,3,4,5,6])
slic=nums[2:5]
print("array:",slic)

slic[0]=10
print("array:",slic)
print("array:",nums) 

#if we want to create copy in array then we can use copy function

slic1=nums[2:5].copy()
print(slic1)
slic1[0]=30
print(slic1)
print(nums)

list: [3, 4, 5]
list: [10, 4, 5]
list: [1, 2, 3, 4, 5, 6]
array: [3 4 5]
array: [10  4  5]
array: [ 1  2 10  4  5  6]
[10  4  5]
[30  4  5]
[ 1  2 10  4  5  6]


Common Data Types in Numpy

- Integers: int32, int64
- Floating point nums: float32, float64
- Boolean: bool
- Complex nums: complex64, complex128
- String: S (byte-str) & U (unicode-str)
- Object: generic python objects - object

In [55]:
#data types in array

a=np.array([1,2,3,4])  
print(a,a.dtype)  #int64  we can downgrade to int16,int8 according to our need
a1 = np.array([1, 2, 3, 4], dtype=np.int16)
print(a1,a1.dtype)

b=np.array([1,2,3,"prime"])
print(b,b.dtype) #all converted to string U(unicode string) type, we also have string s type

#note : numpy is mostly used for numerical operation so it is very rare to use string in array


#object data type
c = np.array([{7, 8.2, 6}, 1, 2, 3, "prime"])
print(c,c.dtype)  #if there are mixture of lots of data types then python just give object as dtype

#complex number (ex. 2+3j,5+4j etc.)

d=np.array([4 + 5j])  #cannot take i,Python uses j instead of i to represent the imaginary part of complex numbers because i is not defined as an imaginary unit in Python syntax.
print(d,d.dtype)
e=np.array([2 + 3j])

print(d+e,d-e)

[1 2 3 4] int64
[1 2 3 4] int16
['1' '2' '3' 'prime'] <U21
[{8.2, 6, 7} 1 2 3 'prime'] object
[4.+5.j] complex128
[6.+8.j] [2.+2.j]


Axes in Multi-dimensional Arrays

- 1D array has 1 axis (axis0).
- 2D array has 2 axes (axis0 = rows, axis1 = columns)
- 3D array has 3 axes (axis0 = depth/layer, axis1 = rows in each layer, axis2 = columns in each layer)

In [56]:
#multidimensional arrays

f=np.array([1,2,3]) #1D array
print(f,f.shape,f[1])

g=np.array([[1,2,3],[4,5,6]]) #2D array
print(g,g.shape,g[0,1]) #g[raw,column] is used to access the elemnt of 2D array
print(g[:,1:2])  #also we can use slicing in array

h=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #3D array
print(h,h.shape)
print(h[0,1,1])  #h[axis,raw,column]
print(h[:,:1,2:])    
#in 3D array there will be combination of 2D arrays each 2D array count as axis, so 1st 2D array axis=0 and so on

[1 2 3] (3,) 2
[[1 2 3]
 [4 5 6]] (2, 3) 2
[[2]
 [5]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
5
[[[3]]

 [[9]]]


***

### Vectorization & Broadcasting

<b>1. Vectorization</b>: It is the process of applying operations to entire arrays or sequences of data at once, rather than iterating through individual elements using explicit loops. 

<b>2. Broadcasting</b>: It is a mechanism that allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them (creating copies of the smaller array to match the larger array's shape). 

<b> Broadcasting Condition <b>

For broadcasting to happen the dimensions should be compatible. Numpy compares shape element-wise. It starts dimension comparison with the trailing (i.e. rightmost) dimension and works its way left. 
Two dimensions are compatible when <ol> <li>they are equal, or</li> <li>one of them is 1. </li>

In [59]:
# Vectorization & Broadcasting

#Vectorization
i = np.array([1, 2, 3, 4, 5])

sq_arr = i ** 2       #square of all nums
print(sq_arr)

j = np.array([6, 7, 8, 9, 10])
print(i + j)


#Broadcasting
arr_mul10 = i * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


***

### Mathematical Functions in NumPy
There are lots of important & commonly used mathematical functions in NumPy.
1. Aggregation functions
   - sum()
   - prod()
   - min() & argmin() - min val & idx of min val
   - max() & argmax() - max val & idx of max val
   - mean()
   - median()
   - std() - standard deviation
   - var() - variance

In [60]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


2. Power functions
   - square()
   - sqrt() - square root
   - pow(a, b) - a^b

In [ ]:
print(np.square(arr))    # [1, 4, 9, 16, 25]
print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))    # [1, 8, 27, 64, 125]

3. Log & Exponential functions
   - log() - natual log
   - log10() - log base 10
   - log2() - log base 2
   - exp() - exponentional i.e. e^x

In [61]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


4. Rounding functions
   - round() - rounds to nearest value
   - floor() - rounds down
   - ceil() - rounds up
   - trunc() - truncates decimal part

In [63]:
print(np.round(2.678))    # 3.0
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0
print(np.trunc(2.678))    # 2.0

3.0
2.0
3.0
2.0


5. Additional functions
   - abs() - absolute value
   - sort()
   - unique() - returns unique values

+ there are additionally a lot more useful functions that we'll study later.

In [64]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
