In [4]:
import torch 
import torch.nn as nn

In [6]:
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [7]:
neuron=nn.Linear(3,1)

In [9]:
output=neuron(inputs)
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [10]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [11]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [13]:
#verify using formula = xi.wi + bias

op=neuron.weight @ inputs + neuron.bias
op

tensor([1.5244], grad_fn=<AddBackward0>)